spring:
  application:
    name: justificativo-service
  datasource:
    url: jdbc:mysql://localhost:3306/bdmicros
    username: root
    password: Angelito2021
jpa:
  hibernate:
    ddl-auto: update
server:
  port: 8003
  forward-headers-strategy: framework
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}